### ISSUE TITLE
Error in deleteMarkedReadings function

### ISSUE THREAD

**Issue by CarsonHerness** [CEHAT-Clinic/dashboard#582]
From Firestore cloud functions logs:

- `Error: Process exited with code 16`
- ```Error detected in deleteMarkedReadings {"errorGroup":"CK6l8ZWRse7CXA","@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.Insight","errorEvent":{"eventTime":"2021-04-10T21:42:04.193Z","message":"Error: 14 UNAVAILABLE: The datastore operation timed out, or the data was temporarily unavailable.```
- `Error: 4 DEADLINE_EXCEEDED: Deadline exceeded`

**Comment by CarsonHerness** [comment]
```
Error: 9 FAILED_PRECONDITION: The 'read_time' cannot be more than 270 seconds in the past. The requested value was '2021-04-13T21:40:04.563429Z', but the minimum allowed value was '2021-04-13T21:40:50.028520Z'.
    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:327:49)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at process.nextTick (/workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:130:78)
    at process._tickCallback (internal/process/next_tick.js:61:11) 
```
